---
azs:
- name: z1

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.0.0/24
    gateway: 10.244.0.1
    az: z1

vm_types:
- name: default

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  network: default
